### PR TITLE
Replaced MessageEmbed with RichEmbed

### PR DESCRIPTION
**Pull request by JonasPardon**
Using MessageEmbed to send embeds is bad practice, the RichEmbed class should be used instead. More here: https://discord.js.org/#/docs/main/stable/class/MessageEmbed

### CODE REVIEW

**Comment by Vezqi** [comment]
AlphaConsoleBot is using the stable version of discord.js, which uses MessageEmbed.

**Comment by ThePjpollie** [comment]
Your link links to stable version of Discord.JS
We are using the master version due to stable not being able to create channels in category's yet.

Master version does not have RichEmbed as far as I know so that's why we are using MessageEmbed.

**Comment by ThePjpollie** [comment]
I have tried one out of interest to confirm my statement. After trying it resulted in an error:

```
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Discord.RichEmbed is not a constructor
```

Whilst MessageEmbed worked fine.

**Comment by JonasPardon** [comment]
Fair point, didn't notice you guys using the master branch.

**Pull request closed without merging**
